version: "3.1"

services:
  db:
    image: jenkins/jenkins:lts
    container_name: jenkins-build-deploy
    restart: always
    volumes:
      - jenkins-data:/var/jenkins_home
    ports:
      - "8999:8080"

volumes:
  jenkins-data:
